main/urls.py
from django.urls import path

from .views import UserDetailView, UserUpdateView, UserListView, SendFriendRequestView, FriendRequestListView, \
    FriendRequestAcceptView, FriendRequestRejectView

app_name = 'main'
urlpatterns = [
    path('user/<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('user/<int:pk>/update/', UserUpdateView.as_view(), name='user-update'),
    path('user/list/', UserListView.as_view(), name='user-list'),
    path('user/send-friend-request/', SendFriendRequestView.as_view(), name='send-friend-request'),
    path('user/friend-request-list/', FriendRequestListView.as_view(), name='friend-request-list'),
    path('accept/<int:pk>/', FriendRequestAcceptView.as_view(), name='accept'),
    path('reject/<int:pk>/', FriendRequestRejectView.as_view(), name='reject'),

]

posts/urls.py
from django.template.context_processors import static
from django.urls import path

from publi import settings
from . import views
app_name = 'posts'
urlpatterns = [
    path('', views.PostList.as_view(), name='post_list'),
    path('<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
    path('create/', views.PostCreate.as_view(), name='post_create'),
    path('<int:pk>/update', views.PostUpdateView.as_view(), name='post_update'),
    path('<int:pk>/delete/', views.PostDelete.as_view(), name='post_delete'),
    path('<int:pk>/save/', views.SavePost.as_view(), name='save_post'),
]

publi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('posts.urls')),
    path('', include('main.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from django.contrib.auth.models import User

from publi import settings


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='post_images/')
    text = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    liked_by = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='liked_posts', blank=True)
    saved_by = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='saved_posts', blank=True)

    def __str__(self):
        return f"Post by {self.user.email}"
    def get_like_count(self):
        return self.liked_by.count()


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    text = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comment by {self.user.email} on {self.post}"

posts/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['image', 'text']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

posts/views.py
from django.http import HttpResponseBadRequest
from django.shortcuts import redirect, get_object_or_404, render
from django.views import View
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, FormView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .models import Post, Comment
from .forms import PostForm, CommentForm

class PostList(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'posts/post_list.html'
    context_object_name = 'posts'
    ordering = ['-created_date']

class PostDetail(View):
    def get(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        return render(request, 'posts/post_detail.html', {'post': post})

    def post(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        if 'like' in request.POST:
            if request.user in post.liked_by.all():
                post.liked_by.remove(request.user)
            else:
                post.liked_by.add(request.user)
        elif 'comment' in request.POST:
            text = request.POST['comment_text']
            Comment.objects.create(user=request.user, post=post, text=text)
        return redirect('posts:post_detail', pk=post.pk)

class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = 'posts/post_create.html'
    success_url = reverse_lazy('posts:post_list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class PostUpdateView(UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'posts/post_update.html'
    context_object_name = 'post'
    success_url = reverse_lazy('posts:post_list')

class PostDelete(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'posts/post_delete.html'
    context_object_name = 'post'
    success_url = reverse_lazy('posts:post_list')

class SavePost(LoginRequiredMixin, View):
    def post(self, request, pk):
        post = Post.objects.get(pk=pk)
        # Perform save post action here
        return redirect('posts:post_list', pk=post.pk)

templates/posts/post_create.html
{% extends 'base.html' %}
{% block content %}
<div class="min-h-screen flex flex-col text-2xl font-Ubuntu  items-center justify-center ">
    <h1 class="text-2xl font-bold">+Add Post</h1>
    <div class="bg-custum-lite-green px-2 py-2 rounded shadow-md text-black max-w-lg  flex flex-col  items-center justify-center ">

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
            <span class="text-xl py-2 px-8">{{ field }}</span>
            {%endfor%}
            <button type="submit" class="bg-custom-bg hover:bg-custom-bg text-white font-bold py-2 px-4 rounded">
                +add post
            </button>
        </form>
    </div>
</div>

{% endblock content %}

templates/posts/post_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="min-h-screen flex flex-col text-2xl font-Ubuntu  items-center justify-center ">
    <h1 class="text-2xl font-bold">-Delete Post</h1>
    <div class="bg-custum-lite-green px-2 py-2 rounded shadow-md text-black max-w-lg  flex flex-col  items-center justify-center ">
        <span class="text-xl py-2 px-8"><p>Created by: {{ post.user }}</p></span>
        <img src="{{ post.image }}" class="text-xl py-2 px-8">
        <span class="text-xl py-2 px-8"><p>{{ post.text }}</p></span>
        <span class="text-xl py-2 px-8"><p>{{ post.created_date }}</p></span>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="bg-custom-bg hover:bg-custom-bg text-white font-bold py-2 px-4 rounded">Delete Post</button>
        </form>
    </div>
</div>

{% endblock content %}

templates/posts/post_detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="font-Ubuntu text-xl">
    <div href="{% url 'posts:post_detail' pk=post.pk %}" class="flex items-center justify-center">
        <div class="m-4 p-4 bg-white border border-gray-300 rounded shadow-md">
            <div class="flex items-center">
                <img class="w-8 h-8 rounded-full" src="{{ user.profile_image.url }}"/>
                <p class="font-bold py-2 px-2">{{ post.user }}</p>
                {% if post.user == request.user %}
                <div class="relative">
                    <button type="button" class="flex items-center focus:outline-none dropdown-toggle">:</button>
                    <div class="absolute right-0 mt-2 py-2 w-48 bg-white rounded shadow-lg hidden dropdown-menu">
                        <a class="block px-4 py-2 text-gray-800 hover:bg-gray-100"
                           href="{% url 'posts:post_update' pk=post.pk %}">Update</a>
                        <a class="block px-4 py-2 text-gray-800 hover:bg-gray-100"
                           href="{% url 'posts:post_delete' pk=post.pk %}">Delete</a>
                    </div>
                </div>
                {% endif %}
            </div>
            <img src="{{ post.image.url }}" class="w-150 h-150 mt-2">
            <div class="flex items-center justify-center space-x-4">
                <form method="POST" action="{% url 'posts:post_detail' pk=post.pk %}">
                    {% csrf_token %}
                    <button type="submit" name="like" class="text-red-600">
                        {% if request.user in post.liked_by.all %}
                        <span class="fas fa-heart text-red-600"></span>
                        {% else %}
                        <span class="far fa-heart"></span>
                        {% endif %} {{ post.liked_by.count }}
                    </button>
                </form>
            </div>
            <p class="mt-2">{{ post.text }}</p>
            <p class="text-gray-500 text-sm mt-2">{{ post.created_date }}</p>
            <hr>
            <div class="mt-4">
                <h3>Comments:</h3>
                {% for comment in post.comments.all %}
                <p class="bg-gray-100 rounded-lg px-4 py-2 text-sm mt-2">{{ comment.text }}</p>
                {% endfor %}
                <form method="POST" action="{% url 'posts:post_detail' pk=post.pk %}">
                    {% csrf_token %}
                    <input type="text" name="comment_text" placeholder="Add a comment"
                           class="border border-gray-300 rounded-lg px-4 py-2 mt-2">
                    <button type="submit" name="comment"
                            class="bg-custom-bg hover:bg-custom-bg text-white font-bold py-2 px-4 rounded mt-2">Post
                        Comment
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    const dropdownToggle = document.querySelector('.dropdown-toggle');
    const dropdownMenu = document.querySelector('.dropdown-menu');

    dropdownToggle.addEventListener('click', function () {
        dropdownMenu.classList.toggle('hidden');
    });
</script>
{% endblock content %}

templates/posts/post_list.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div class="font-Ubuntu text-xl">
    {% for post in posts %}
    <a href="{% url 'posts:post_detail' pk=post.pk %}" class="flex items-center justify-center">
        <div class="m-4 p-4 bg-white border border-gray-300 rounded shadow-md">
            <div class="flex items-center">
                <img class="w-8 h-8 rounded-full" src="{{ user.profile_image.url }}"/>
                <p class="font-bold py-2 px-2">{{ post.user }}</p>

            </div>
            <img src="{{ post.image.url }}" class="w-150 h-150 mt-2">
            <div class="flex items-center justify-center space-x-4">
                <i class="fa-solid bg-red-700 fa-heart"></i> {{ post.get_like_count }}
                <i class="fa-solid fa-comment"></i>{{ post.comments.count }}
            </div>
            <p class="mt-2">{{ post.text }}</p>
            <p class="text-gray-500 text-sm mt-2">{{ post.created_date }}</p>
        </div>
    </a>
    {% empty %}
    <p>No posts available.</p>
    {% endfor %}

</div>
{% endblock content %}

templates/posts/post_update.html
{% extends 'base.html' %}
{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="bg-custom-bg hover:bg-custom-bg text-white font-bold py-2 px-4 rounded mt-2">Update Post</button>
</form>

{% endblock content %}