accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .views import signup_page, login_page, logout_view, activate_account_page

app_name = 'accounts'
urlpatterns = [
    path('accounts/signup/', signup_page, name='signup'),
    path('accounts/activate/<slug:uidb64>/<slug:token>/', activate_account_page, name='activate'),
    path('accounts/login/', login_page, name='login'),
    path('accounts/logout/', logout_view, name='logout'),


    # Reset Passoword Urls
    path('accounts/reset-password', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'),
         name='reset_password'),
    path('accounts/password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_sent.html'),
         name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_form.html'),
         name='password_reset_confirm'),
    path('accounts/reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_complete'),

]


# To update password reset functionality

main/urls.py
from django.urls import path

from .views import UserDetailView, UserUpdateView, UserListView, SendFriendRequestView, FriendRequestListView, \
    FriendRequestAcceptView, FriendRequestRejectView

app_name = 'main'
urlpatterns = [
    path('user/<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('user/<int:pk>/update/', UserUpdateView.as_view(), name='user-update'),
    path('user/list/', UserListView.as_view(), name='user-list'),
    path('user/send-friend-request/', SendFriendRequestView.as_view(), name='send-friend-request'),
    path('user/friend-request-list/', FriendRequestListView.as_view(), name='friend-request-list'),
    path('accept/<int:pk>/', FriendRequestAcceptView.as_view(), name='accept'),
    path('reject/<int:pk>/', FriendRequestRejectView.as_view(), name='reject'),

]

publi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('posts.urls')),
    path('', include('main.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.urls import reverse

from publi import settings

class UserManager(BaseUserManager):
    def create_user(self, email, password=None, is_staff=False, is_admin=False, is_active=True): # may look repetitive adding staff, admin and active status, but it simplifies the
                                                                                        # work when using create_staffuser() and create_superuser()
        if not email:
            raise ValueError("User must have an email address")
        if not password:
            raise ValueError('User must have a password')
        user_obj = self.model(email=self.normalize_email(email))
        user_obj.set_password(password)
        user_obj.is_active = is_active
        user_obj.admin = is_admin
        user_obj.staff = is_staff
        user_obj.save(using=self._db)
        return user_obj

    def create_staffuser(self, email, password=None):
        user = self.create_user(email, password=password, is_staff=True)
        return user

    def create_superuser(self, email, password=None):
        user = self.create_user(email, password=password, is_staff=True, is_admin=True)
        return user


class User(AbstractBaseUser):
    email = models.EmailField(unique=True, max_length=255)
    first_name = models.CharField(max_length=30,null=True)
    last_name = models.CharField(max_length=30,null=True)
    biography = models.CharField(max_length=300,null=True)
    profile_image = models.ImageField(upload_to='profile_images/',default='default.jpg')
    is_active = models.BooleanField(default=True)
    staff = models.BooleanField(default=False)
    admin = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = 'email'

    objects = UserManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    def get_absolute_url(self):
        return reverse('main:user-detail', kwargs={'pk': self.pk})

    @property
    def is_staff(self):
        return self.staff

    @property
    def is_admin(self):
        return self.admin

    """@property
    def is_active(self):
        return self.is_active"""


class LoginAttempt(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    login_attempts = models.IntegerField(default=0)
    timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return 'user: {}, attempts: {}'.format(self.user.email, self.login_attempts)


class FriendshipRequest(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_friendship_requests')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='received_friendship_requests')
    status = models.CharField(choices=(('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')), default='pending', max_length=10)
    created_date = models.DateTimeField(auto_now_add=True)

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.forms import ModelForm
User = get_user_model()


class UserAdminCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email',)

    def clean_password2(self): # checking that the two passwords match
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Passwords do not match')
        return password2

    def save(self, commit=True): # save he proovided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    ''' A form for updating users, includes all the fields on the user, but
    replaces the password fields with admin's password hash display field. '''

    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'password', 'is_active', 'admin')

    def clean_password(self):
        ''' Regardless of what the user provides retrun the initial value.
        This is done here rather than on the field, because the field does
        not have access to the initial value. '''
        return self.initial['password']


class LoginForm(forms.Form):
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input',
                                                                           'placeholder': 'Enter email'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-input',
                                                                                   'placeholder': 'Enter password'}))


class RegistrationForm(forms.ModelForm):
    '''A form for creating new users. Includes all required fields plus
    repeated password'''
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-input', 'placeholder': 'Enter password'}))
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput(attrs={'class': 'form-input', 'placeholder': 'Confirm password'}))

    class Meta:
        model = User
        fields = ['email']
        widgets = {'email': forms.EmailInput(attrs={'class': 'form-input', 'placeholder': 'Enter Email'})}

    def clean_password2(self):  # checking that the two passwords match
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Passwords do not match')
        return password2

    def save(self, commit=True): # save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.is_active = False
            user.save()
        return user


class UpdateUserForm(forms.ModelForm):
    username = forms.CharField(max_length=100,required=True,widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(required=True,widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'email']


class UpdateProfileForm(forms.ModelForm):
    profile_image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control-file'}))
    bio = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 5}))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'profile_image', 'biography']

accounts/views.py
from datetime import timedelta

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.encoding import force_str
from django.utils.http import urlsafe_base64_decode

from accounts.forms import UpdateUserForm, UpdateProfileForm
from .forms import RegistrationForm, LoginForm
from .models import LoginAttempt, User
from .token import account_activation_token
from .decorators import unauthenticated_user
from .utils import send_user_email


@unauthenticated_user
def signup_page(request):
    form = RegistrationForm()
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            to_email = form.cleaned_data.get('email')
            current_site = get_current_site(request)
            mail_subject = 'Activate your account'
            response = send_user_email(user, mail_subject, to_email, current_site, 'accounts/email_verification.html')
            if response == 'success':
                messages.success(request, "We have sent you an activation link in your email. Please confirm your"
                                          "email to continue. Check your spam folder if you don't receive it")
            else:
                messages.error(request, 'An error occurred. Please ensure you have good internet connection and you have entered a valid email address')
                user.delete()
        else:
            if form.errors:
                for field in form:
                    for error in field.errors:
                        messages.error(request, error)
            form = RegistrationForm()

    context = {
        'form': form
    }
    return render(request, 'accounts/signup.html', context)


@unauthenticated_user
def login_page(request):
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            now = timezone.now()
            try:
                _user = User.objects.get(email=email)
                login_attempt, created = LoginAttempt.objects.get_or_create(user=_user)  # get the user's login attempt
                if (login_attempt.timestamp + timedelta(seconds=settings.LOGIN_ATTEMPTS_TIME_LIMIT)) < now:
                    user = authenticate(request, username=email, password=password)
                    if user is not None:
                        login(request, user)
                        login_attempt.login_attempts = 0    # reset the login attempts
                        login_attempt.save()
                        return redirect(settings.LOGIN_REDIRECT_URL)  # change expected_url in your project

                    else:
                        login_attempt.login_attempts += 1
                        login_attempt.timestamp = now
                        login_attempt.save()
                        if login_attempt.login_attempts == settings.MAX_LOGIN_ATTEMPTS:
                            _user.is_active = False
                            _user.save()
                            # send the re-activation email
                            mail_subject = "Account suspended"
                            current_site = get_current_site(request)
                            send_user_email(_user, mail_subject, email, current_site, 'accounts/email_account_suspended.html')
                            messages.error(request, 'Account suspended, maximum login attempts exceeded. '
                                                    'Reactivation link has been sent to your email')
                        else:
                            messages.error(request, 'Incorrect email or password')
                        return redirect(settings.LOGIN_URL)
                else:
                    messages.error(request, 'Login failed, please try again')
                    return redirect(settings.LOGIN_URL)

            except ObjectDoesNotExist:
                messages.error(request, 'Incorrect email or password')
                return redirect(settings.LOGIN_URL)
        else:
            if form.errors:
                for field in form:
                    for error in field.errors:
                        messages.error(request, error)
    context = {'form': form}
    return render(request, 'accounts/login.html', context)


def activate_account_page(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login_attempt, created = LoginAttempt.objects.get_or_create(user=user)
        if login_attempt.login_attempts >= settings.MAX_LOGIN_ATTEMPTS:
            login_attempt.login_attempts = 0
            login_attempt.save()
            messages.success(request, 'Account restored, you can now proceed to login')
        else:
            messages.success(request, 'Thank you for confirming your email. You can now login.')
        return redirect(settings.LOGIN_URL)
    else:
        messages.error(request, 'Activation link is invalid!')
        return redirect(settings.LOGIN_URL)


def logout_view(request):
    logout(request)
    return redirect(settings.LOGOUT_REDIRECT_URL)


@login_required
def profile(request):
    if request.method == 'POST':
        user_form = UpdateUserForm(request.POST, instance=request.user)
        profile_form = UpdateProfileForm(request.POST, request.FILES, instance=request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile is updated successfully')
            return redirect(to='users-profile')
    else:
        user_form = UpdateUserForm(instance=request.user)
        profile_form = UpdateProfileForm(instance=request.user.profile)

    return render(request, 'users/profile.html', {'user_form': user_form, 'profile_form': profile_form})

templates/accounts/email_account_suspended.html
{% autoescape off %}
Hi {{ user.username }},
We have detected suspicious activity on your account. Maximum login attempts
have been exceeded, as a result your account has been suspended.

Click the link below to reactivate your account.
http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}

templates/accounts/email_verification.html
{% autoescape off %}
Hi ,
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}

templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
<div class=" min-h-screen flex flex-col text-2xl font-Ubuntu">
    <div class="container max-w-sm mx-auto flex-1 flex flex-col items-center justify-center px-2">
        <div class="bg-white px-6 py-8 rounded shadow-md text-black w-full">
            <h1 class="mb-8 text-3xl text-center">Login</h1>

            <form method="POST" id="signup-form" class="signup-form">
                {% csrf_token %}
                {% for field in form %}
                <div class="w-full shadow-md bg-custum-lite-green text-center px-2 py-2 rounded focus:outline-none my-5">
                     <span class="text-xl py-4 px-2">{{ field }}</span>
                </div>
                {% endfor %}
                <button style="background: #115e59;"
                        type="submit"  value="sign-in"
                        class="w-full text-center py-3 rounded bg-green hover:bg-green-dark focus:outline-none my-1"
                >Login
                </button>
            </form>
            {% include 'accounts/messages.html' %}

            <p class="text-center">
                Don't have an account ? <a href="{% url 'accounts:signup' %}" class="text-custom-dark-green">Register here</a>
            </p>

        </div>
    </div>
</div>


{% endblock content %}

templates/accounts/messages.html
      <div class="col-md-12">
        {% if messages %}
          {% for message in messages %}
             {% if message.tags == 'success' %}
                <div class="alert alert-success alert-with-icon">
                  <button type="button" aria-hidden="true" class="close" data-dismiss="alert" aria-label="Close">
                    <i class="tim-icons icon-simple-remove"></i>
                  </button>
                  <span data-notify="icon" class="tim-icons icon-bell-55"></span>
                  <span data-notify="message">{{ message }}</span>
                </div>
             {% else %}
                <div class="alert alert-warning alert-with-icon">
                  <button type="button" aria-hidden="true" class="close" data-dismiss="alert" aria-label="Close">
                    <i class="tim-icons icon-simple-remove"></i>
                  </button>
                  <span data-notify="icon" class="tim-icons icon-alert-circle-exc"></span>
                  <span data-notify="message">{{ message }}</span>
                </div>
            {% endif %}
          {% endfor %}
        {% endif %}
      </div>

templates/accounts/password_reset.html
{% extends 'accounts/base.html' %}
{% block content %}
{% load crispy_forms_tags %}


<div class=" min-h-screen flex flex-col">
    <div class="container max-w-sm mx-auto flex-1 flex flex-col items-center justify-center px-2">
        <div class="bg-white px-6 py-8 rounded shadow-md text-black w-full">
            <form method="POST" id="signup-form" class="signup-form">
                {% csrf_token %}
                <h2 class="form-title">Password Reset</h2>
                <div class="mb-3">
                    {{ form|crispy }}
                </div>
                <div class="form-group">
                    <input type="submit" name="submit" id="submit" class="form-submit" value="Send Reset Email"/>
                </div>
            </form>

            {% include 'accounts/messages.html' %}

            <p class="loginhere">
                Don't have an account ? <a href="{% url 'accounts:signup' %}" class="loginhere-link">Sign Up here</a>
            </p>
            <p class="loginhere">
                Have already an account ? <a href="{% url 'accounts:login' %}" class="loginhere-link">Login here</a>
            </p>
        </div>
    </div>
</div>

{% endblock content %}

templates/accounts/password_reset_done.html
{% extends 'accounts/base.html' %}
{% block content %}


<div class=" min-h-screen flex flex-col">
    <div class="container max-w-sm mx-auto flex-1 flex flex-col items-center justify-center px-2">
        <div class="bg-white px-6 py-8 rounded shadow-md text-black w-full">
            <h2 class="form-title">Password reset complete</h2>
            <p>Your password has been set. You may go ahead and log in now.</p>

            <p class="loginhere">
                <a href="{% url 'accounts:login' %}" class="loginhere-link">Login here</a>
            </p>
        </div>
    </div>
</div>

{% endblock content %}

templates/accounts/password_reset_form.html
{% extends 'accounts/base.html' %}
{% block content %}
{% load crispy_forms_tags %}


<div class=" min-h-screen flex flex-col">
    <div class="container max-w-sm mx-auto flex-1 flex flex-col items-center justify-center px-2">
        <div class="bg-white px-6 py-8 rounded shadow-md text-black w-full">
            <form method="POST" id="signup-form" class="signup-form">
                {% csrf_token %}
                <h2 class="form-title">Enter new password</h2>
                <div class="mb-3">
                    {{ form|crispy }}
                </div>
                <div class="form-group">
                    <input type="submit" name="submit" id="submit" class="form-submit" value="Submit"/>
                </div>
            </form>

            {% include 'accounts/messages.html' %}

        </div>
    </div>
</div>

{% endblock content %}

templates/accounts/password_reset_sent.html
{% extends 'accounts/base.html' %}
{% block content %}

<div class=" min-h-screen flex flex-col">
    <div class="container max-w-sm mx-auto flex-1 flex flex-col items-center justify-center px-2">
        <div class="bg-white px-6 py-8 rounded shadow-md text-black w-full">
            <h2 class="form-title">Password reset sent</h2>

            <p style="">We’ve emailed you instructions for setting your password, if an account exists with the email
                you entered. You should receive them shortly.</p>

            <p style="">If you don’t receive an email, please make sure you’ve entered the address you registered with,
                and check your spam folder.</p>

            <p class="loginhere mt-3">
                Go back to <a href="{% url 'accounts:login' %}" class="loginhere-link">Login here</a>
            </p>

        </div>
    </div>
</div>

{% endblock content %}

templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}

<div class="min-h-screen flex flex-col text-2xl font-Ubuntu">
    <div class="container max-w-sm mx-auto flex-1 flex flex-col items-center justify-center px-2">
        <div class="bg-white px-6 py-8 rounded shadow-md text-black w-full">
            <h1 class="mb-8 text-3xl text-center">Register</h1>

            <form method="POST" id="signup-form" class="signup-form">
                {% csrf_token %}
                {% for field in form %}
                <div class="w-full shadow-md bg-custum-lite-green text-center px-2 py-2 rounded focus:outline-none my-5">
                     <span class="text-xl py-4 px-2">{{ field }}</span>
                </div>
                {% endfor %}
                <button style="background: #115e59;"
                        type="submit" value="sign-up"
                        class="w-full text-center py-3 rounded-full bg-green hover:bg-green-dark focus:outline-none my-1"
                >Create
                </button>
            </form>
            {% include 'accounts/messages.html' %}

            <p class="text-center">
                Have already an account? <a href="{% url 'accounts:login' %}" class="text-custom-dark-green">Login here</a>
            </p>

        </div>
    </div>
</div>

{% endblock content %}