main/urls.py
from django.urls import path

from .views import UserDetailView, UserUpdateView, UserListView, SendFriendRequestView, FriendRequestListView, \
    FriendRequestAcceptView, FriendRequestRejectView

app_name = 'main'
urlpatterns = [
    path('user/<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('user/<int:pk>/update/', UserUpdateView.as_view(), name='user-update'),
    path('user/list/', UserListView.as_view(), name='user-list'),
    path('user/send-friend-request/', SendFriendRequestView.as_view(), name='send-friend-request'),
    path('user/friend-request-list/', FriendRequestListView.as_view(), name='friend-request-list'),
    path('accept/<int:pk>/', FriendRequestAcceptView.as_view(), name='accept'),
    path('reject/<int:pk>/', FriendRequestRejectView.as_view(), name='reject'),

]

publi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('posts.urls')),
    path('', include('main.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

main/forms.py
from django import forms
from accounts.models import User

class FriendRequestForm(forms.Form):
    user_id = forms.IntegerField(widget=forms.HiddenInput())


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'biography', 'profile_image']

main/views.py
from django.db.models import Q
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import DetailView, FormView, UpdateView, ListView
from accounts.models import User, FriendshipRequest
from main.forms import FriendRequestForm

class UserListView(ListView):
    model = User
    template_name = 'main/user_list.html'
    context_object_name = 'users'
    paginate_by = 10

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            return User.objects.filter(
                Q(username__icontains=query) |
                Q(full_name__icontains=query)
            )
        return User.objects.all()

class UserDetailView(DetailView):
    model = User
    template_name = 'main/user_detail.html'
    context_object_name = 'user'

class UserUpdateView(UpdateView):
    model = User
    template_name = 'main/user_update.html'
    fields = ['first_name', 'last_name', 'biography', 'profile_image']


class SendFriendRequestView(FormView):
    template_name = 'send_friend_request.html'
    form_class = FriendRequestForm
    success_url = '/user/list/'  # Redirect to the user list page after sending the friend request

    def form_valid(self, form):
        return super().form_valid(form)

class FriendRequestListView(View):
    def get(self, request):
        friend_requests = FriendshipRequest.objects.filter(receiver=request.user)
        return render(request, 'main/list.html', {'friend_requests': friend_requests})

class FriendRequestAcceptView(View):
    def post(self, request, pk):
        friend_request = FriendshipRequest.objects.get(pk=pk)
        friend_request.status = 'accepted'
        friend_request.save()
        # Additional logic to create chat room and perform other actions
        return redirect('main:friend-request-list')

class FriendRequestRejectView(View):
    def post(self, request, pk):
        friend_request = FriendshipRequest.objects.get(pk=pk)
        friend_request.status = 'rejected'
        friend_request.save()
        return redirect('main:friend-request-list')

templates/main/list.html
{% extends 'base.html' %}
{% block content %}
    <div class="py-8">
        {% for friend_request in friend_requests %}
            <div class="mb-4">
                <p class="text-lg font-bold">Sender: {{ friend_request.sender.email }}</p>
                <p class="text-lg">Status: {{ friend_request.status }}</p>
                {% if friend_request.status == 'pending' %}
                    <form action="{% url 'main:accept' pk=friend_request.pk %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">Accept</button>
                    </form>
                    <form action="{% url 'main:reject' pk=friend_request.pk %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">Reject</button>
                    </form>
                {% endif %}
            </div>
        {% empty %}
            <p class="text-lg">No friend requests found.</p>
        {% endfor %}
    </div>
{% endblock content %}

templates/main/user_detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="min-h-screen flex flex-col text-2xl font-Ubuntu">
    <div class="container max-w-sm mx-auto flex-1 flex flex-col items-center justify-center px-2">
            <h1 class="text-2xl font-bold ">User Profile</h1>
        <div class="bg-white px-6 py-8 rounded shadow-md text-black w-full">
            <p class="text-lg"><strong>First Name:</strong> {{ user.first_name }}</p>
            <p class="text-lg"><strong>Last Name:</strong> {{ user.last_name }}</p>
            <p class="text-lg"><strong>Email:</strong> {{ user.email }}</p>
            <p class="text-lg"><strong>Biography:</strong> {{ user.biography }}</p>
            <div class="mt-4">
                <strong class="text-lg">Profile Image:</strong>
                <img src="{{ user.profile_image.url }}" class="w-32 h-32 rounded-full mt-2">
            </div>
        </div>
    </div>

{% endblock content %}

templates/main/user_list.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div class="flex flex-col items-center">
  <h1 class="text-2xl font-bold">User List</h1>
  <form method="GET" action="{% url 'main:user-list' %}" class="mt-4">
    <input type="text" name="q" placeholder="Search users" class="px-4 py-2 border border-gray-300 rounded mr-2">
    <button type="submit" class="bg-custom-bg hover:bg-custom-bg text-white font-bold py-2 px-4 rounded mt-2">Search</button>
  </form>
  {% for user in users %}

 {% if  user.id != request.user.id %}
    <div class="mt-8">
      <h2 class="text-xl font-bold">{{ user.email }}</h2>
      <p class="text-lg">{{ user.first_name }}</p>
      <p class="text-lg">{{ user.last_name }}</p>
      <p class="text-lg">{{ user.biography }}</p>
      <form method="POST" action="{% url 'main:send-friend-request' %}" class="mt-2">
        {% csrf_token %}
        <input type="hidden" name="user_id" value="{{ user.id }}">
        <button type="submit" class="bg-custom-bg hover:bg-custom-bg text-white font-bold py-2 px-4 rounded mt-2">Send Friend Request</button>
      </form>
    </div>

 {% endif %}
  {% endfor %}
</div>

{% endblock content %}

templates/main/user_update.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div class="min-h-screen flex flex-col text-2xl font-Ubuntu">
    <div class="container max-w-sm mx-auto flex-1 flex flex-col items-center justify-center px-2">
        <div class="bg-white px-6 py-8 rounded shadow-md text-black w-full">
            <h1 class="text-2xl font-bold">Update Profile</h1>

            <img src="{{ user.profile_image.url }}" class="w-32 h-32 rounded-full mt-2">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                {% for field in form %}
                <div class="w-full shadow-md bg-custum-lite-green text-center px-2 py-2 rounded focus:outline-none my-5">
                    <span class="text-xl py-8 px-2">
                        <span class="text-xl py-8 px-2">{{ field }}</span>
                    </span>
                </div>
                {%endfor%}
                <button type="submit" class="bg-custom-bg hover:bg-custom-bg text-white font-bold py-2 px-4 rounded">
                    Update
                </button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}