accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .views import signup_page, login_page, logout_view, activate_account_page

app_name = 'accounts'
urlpatterns = [
    path('accounts/signup/', signup_page, name='signup'),
    path('accounts/activate/<slug:uidb64>/<slug:token>/', activate_account_page, name='activate'),
    path('accounts/login/', login_page, name='login'),
    path('accounts/logout/', logout_view, name='logout'),


    # Reset Passoword Urls
    path('accounts/reset-password', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'),
         name='reset_password'),
    path('accounts/password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_sent.html'),
         name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_form.html'),
         name='password_reset_confirm'),
    path('accounts/reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_complete'),

]


# To update password reset functionality

main/urls.py
from django.urls import path

from .views import UserDetailView, UserUpdateView, UserListView, SendFriendRequestView, FriendRequestListView, \
    FriendRequestAcceptView, FriendRequestRejectView

app_name = 'main'
urlpatterns = [
    path('user/<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('user/<int:pk>/update/', UserUpdateView.as_view(), name='user-update'),
    path('user/list/', UserListView.as_view(), name='user-list'),
    path('user/send-friend-request/', SendFriendRequestView.as_view(), name='send-friend-request'),
    path('user/friend-request-list/', FriendRequestListView.as_view(), name='friend-request-list'),
    path('accept/<int:pk>/', FriendRequestAcceptView.as_view(), name='accept'),
    path('reject/<int:pk>/', FriendRequestRejectView.as_view(), name='reject'),

]

posts/urls.py
from django.template.context_processors import static
from django.urls import path

from publi import settings
from . import views
app_name = 'posts'
urlpatterns = [
    path('', views.PostList.as_view(), name='post_list'),
    path('<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
    path('create/', views.PostCreate.as_view(), name='post_create'),
    path('<int:pk>/update', views.PostUpdateView.as_view(), name='post_update'),
    path('<int:pk>/delete/', views.PostDelete.as_view(), name='post_delete'),
    path('<int:pk>/save/', views.SavePost.as_view(), name='save_post'),
]

publi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('posts.urls')),
    path('', include('main.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/base.html
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link href="/static/src/style.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet'>
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

</head>
<body class="bg-custum-lite-green">
{% load i18n %}

{% if user.is_authenticated %}
<nav class="fixed bg-custom-bg top-0 left-0 w-full bg-white shadow-md p-2">
    <div class="container flex mx-auto items-center justify-between">
        <a href="{% url 'posts:post_list' %}">{{ user.email }}</a>
        <ul class="flex space-x-4 absolute right-0">
            <li><a href="{% url 'posts:post_create' %}"><i class="fa-solid fa-plus"></i></a></li>
            <li><a href="{% url 'main:user-list' %}"><i class="fa-solid fa-search"></i></a></li>
            <li><a href="{% url 'main:friend-request-list' %}"><i class="fa-solid fa-user-group"></i></a></li>
            <li>
                <div class="relative">
                    <button type="button" class="flex items-center focus:outline-none">
                <img src="{{ user.profile_image.url }}" class="w-8 h-8 rounded-full">
                        <i class="fas fa-caret-down ml-2"></i>
                    </button>
                    <div class="absolute right-0 mt-2 py-2 w-48 bg-white rounded shadow-lg hidden">
                        <a href="{% url 'main:user-detail' pk=user.pk %}"
                           class="block px-4 py-2 text-gray-800 hover:bg-gray-100">User Detail</a>
                        <a href="{% url 'main:user-update' pk=user.pk %}"
                           class="block px-4 py-2 text-gray-800 hover:bg-gray-100">User Update</a>
                        <a href="{% url 'accounts:logout' %}" class="block px-4 py-2 text-gray-800 hover:bg-gray-100">Logout</a>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</nav>
{% endif %}
<div class="container mx-auto mt-16">
    {% block content %}
    {% endblock content %}
</div>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        const dropdownButton = document.querySelector(".relative button");
        const dropdownMenu = document.querySelector(".relative .absolute");

        dropdownButton.addEventListener("click", function () {
            dropdownMenu.classList.toggle("hidden");
        });
    });
</script>
</body>
</html>